'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  ErrorTrackingNavHeader,
  SeverityBadge,
  StatusBadge,
  LoadingState,
  ErrorState,
  PaginationBar,
  formatTimestamp
} from '@web/components/error-tracking/ErrorTrackingComponents';
import { fetchIncidents, type IncidentDto, type ErrorSeverity, type IncidentStatus } from '@web/lib/api-error-tracking';
import '@web/styles/error-tracking.css';

const PAGE_SIZE = 20;

const SEVERITIES: ErrorSeverity[] = ['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

const STATUSES: IncidentStatus[] = ['OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'CLOSED'];

export default function ErrorTrackingIncidentsPage() {
  const router = useRouter();
  const [incidents, setIncidents] = useState<IncidentDto[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [status, setStatus] = useState<IncidentStatus | ''>('');
  const [severity, setSeverity] = useState<ErrorSeverity | ''>('');
  const [serviceName, setServiceName] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const result = await fetchIncidents({
        page,
        limit: PAGE_SIZE,
        status: status || undefined,
        severity: severity || undefined,
        serviceName: serviceName || undefined
      });
      setIncidents(result.items);
      setTotal(result.total);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load incidents');
    } finally {
      setLoading(false);
    }
  }, [page, status, severity, serviceName]);

  useEffect(() => {
    load();
  }, [load]);

  const resetPage = () => setPage(1);

  return (
    <div className="et-container">
      <ErrorTrackingNavHeader activePath="/admin/error-tracking/incidents" />

      <div className="et-card-panel">
        <div className="et-panel-header">
          <div>
            <h1 className="et-panel-title">Incidents</h1>
            <p className="et-panel-subtitle">
              Automatically generated by the incident engine from escalation rules (5–10 occurrences in 300s windows).
            </p>
          </div>
        </div>

        <div className="et-toolbar" role="search" aria-label="Incident filters">
          <input
            type="search"
            className="et-input"
            placeholder="Filter by service name..."
            value={serviceName}
            onChange={(e) => {
              setServiceName(e.target.value);
              resetPage();
            }}
            aria-label="Filter incidents by service"
          />
          <select
            className="et-select"
            value={status}
            onChange={(e) => {
              setStatus(e.target.value as IncidentStatus | '');
              resetPage();
            }}
            aria-label="Filter by lifecycle status"
          >
            <option value="">All statuses</option>
            {STATUSES.map((s) => (
              <option key={s} value={s}>
                {s}
              </option>
            ))}
          </select>
          <select
            className="et-select"
            value={severity}
            onChange={(e) => {
              setSeverity(e.target.value as ErrorSeverity | '');
              resetPage();
            }}
            aria-label="Filter by severity"
          >
            <option value="">All severities</option>
            {SEVERITIES.map((s) => (
              <option key={s} value={s}>
                {s}
              </option>
            ))}
          </select>
        </div>

        {loading && incidents.length === 0 && <LoadingState label="incidents" />}
        {error && <ErrorState message={error} onRetry={load} />}

        {!loading && !error && (
          <div className="et-table-wrap">
            <table className="et-table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Severity</th>
                  <th>Status</th>
                  <th>Service</th>
                  <th>Rule</th>
                  <th>Occurrences</th>
                  <th>First seen</th>
                  <th>Last seen</th>
                </tr>
              </thead>
              <tbody>
                {incidents.length === 0 && (
                  <tr>
                    <td className="et-table-empty" colSpan={8}>
                      No incidents match the current filters.
                    </td>
                  </tr>
                )}
                {incidents.map((incident) => (
                  <tr
                    key={incident.id}
                    tabIndex={0}
                    onClick={() => router.push(`/admin/error-tracking/incidents/${incident.id}`)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        router.push(`/admin/error-tracking/incidents/${incident.id}`);
                      }
                    }}
                  >
                    <td className="et-truncate" title={incident.title}>
                      {incident.title}
                    </td>
                    <td>
                      <SeverityBadge severity={incident.severity} />
                    </td>
                    <td>
                      <StatusBadge status={incident.status} />
                    </td>
                    <td className="et-mono">{incident.serviceName}</td>
                    <td className="et-mono">{incident.ruleId}</td>
                    <td className="et-mono">{incident.occurrenceCount}</td>
                    <td className="et-mono">{formatTimestamp(incident.firstSeenAt)}</td>
                    <td className="et-mono">{formatTimestamp(incident.lastSeenAt)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <PaginationBar
              page={page}
              total={total}
              pageSize={PAGE_SIZE}
              hasMore={page * PAGE_SIZE < total}
              onPageChange={setPage}
            />
          </div>
        )}
      </div>
    </div>
  );
}
