import { sql } from 'drizzle-orm';
import type { NodePgDatabase } from 'drizzle-orm/node-postgres';

export interface TenantContextOptions {
  collegeId: string;
  isSuperAdmin?: boolean;
}

/**
 * Validates that a tenant (college) identifier is safe to use in SQL contexts.
 * Tenant IDs are generated by the platform (UUID-like alphanumeric keys) and must
 * not contain SQL metacharacters such as quotes or semicolons.
 */
const TENANT_ID_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,254}$/;

export function validateTenantId(collegeId: string): void {
  if (!collegeId || !TENANT_ID_PATTERN.test(collegeId)) {
    throw new Error(
      `Invalid tenant identifier: '${collegeId}'. Tenant IDs must be alphanumeric (with optional '-', '_') and 1-255 characters.`
    );
  }
}

/**
 * Escapes a string literal for safe interpolation into PostgreSQL SQL.
 * Uses standard PostgreSQL single-quote doubling so the value cannot break
 * out of the enclosing string literal (SQL injection defense).
 */
export function escapeLiteral(value: string): string {
  return "'" + String(value).replace(/'/g, "''") + "'";
}

/**
 * SQL Helper to enable Row Level Security on a database table
 */
export function enableRlsSql(tableName: string): string {
  return `ALTER TABLE "${tableName}" ENABLE ROW LEVEL SECURITY;`;
}

/**
 * SQL Helper to create tenant isolation policy on a table containing `college_id`
 */
export function createTenantPolicySql(tableName: string): string {
  return `
    DROP POLICY IF EXISTS tenant_isolation_policy ON "${tableName}";
    CREATE POLICY tenant_isolation_policy ON "${tableName}"
      AS RESTRICTIVE
      USING (
        CURRENT_SETTING('app.is_super_admin', true) = 'true' OR
        college_id::text = CURRENT_SETTING('app.current_college_id', true)
      )
      WITH CHECK (
        CURRENT_SETTING('app.is_super_admin', true) = 'true' OR
        college_id::text = CURRENT_SETTING('app.current_college_id', true)
      );
  `.trim();
}

/**
 * SQL statement setting the session-level tenant variables for PostgreSQL RLS evaluation.
 * The collegeId is validated and escaped to prevent SQL injection via malicious tenant
 * identifiers (defense in depth — the primary parameterization happens in withTenantContext).
 */
export function setTenantContextSql(collegeId: string, isSuperAdmin: boolean = false): string {
  validateTenantId(collegeId);
  const superAdminFlag = isSuperAdmin ? 'true' : 'false';
  return `
    SET LOCAL app.current_college_id = ${escapeLiteral(collegeId)};
    SET LOCAL app.is_super_admin = ${escapeLiteral(superAdminFlag)};
  `.trim();
}

/**
 * Parameterized SQL fragment that sets the session-level tenant variables for
 * PostgreSQL RLS evaluation using drizzle's tagged-template parameterization.
 * This is the injection-safe path used by {@link withTenantContext}.
 */
export function setTenantContextParameterized(collegeId: string, isSuperAdmin: boolean = false) {
  validateTenantId(collegeId);
  const adminFlag = isSuperAdmin ? 'true' : 'false';
  return sql`
    SELECT set_config('app.current_college_id', ${collegeId}, true),
           set_config('app.is_super_admin', ${adminFlag}, true)
  `;
}

/**
 * Executes a callback within a transactional context configured with PostgreSQL session-level
 * tenant variables for Row Level Security (RLS).
 */
export async function withTenantContext<T>(
  db: NodePgDatabase<any> | any,
  options: TenantContextOptions,
  callback: (tx: any) => Promise<T>
): Promise<T> {
  validateTenantId(options.collegeId);
  return db.transaction(async (tx: any) => {
    await tx.execute(sql.raw(setTenantContextSql(options.collegeId, options.isSuperAdmin)));
    return callback(tx);
  });
}
